config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  
  resources :powers
  root 'powers#index'   
  
  get '/check', :controller=>'powers', :action=>'checkpower'
  post '/validate', :controller=>'powers', :action=>'power'
  

end

app/models/exception_handler/error.rb
module ExceptionHandler
	class Error < ActiveRecord::Base
		#Table is called "errors"
		#Dev needs to use migration to create db

		#Associations
		belongs_to :usable, polymorphic: true
	end
end

app/models/power.rb
class Power < ActiveRecord::Base
  belongs_to :user
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :powers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exception_handler/exception_controller.rb
module ExceptionHandler
  class ExceptionController < ActionController::Base

    #Response
    respond_to :html, :xml, :json

  	#Dependencies
  	before_action :status, :app_name

    #Layout
    layout :layout_status

    ####################
    #      Action      #
    ####################

  	#Show
    def show
      respond_with status: @status
    end

    ####################
    #   Dependencies   #
    ####################

    protected

    #Info
    def status
      @exception  = env['action_dispatch.exception']
      @status     = ActionDispatch::ExceptionWrapper.new(env, @exception).status_code
      @response   = ActionDispatch::ExceptionWrapper.rescue_responses[@exception.class.name]
    end

    #Format
    def details
      @details ||= {}.tap do |h|
        I18n.with_options scope: [:exception, :show, @response], exception_name: @exception.class.name, exception_message: @exception.message do |i18n|
          h[:name]    = i18n.t "#{@exception.class.name.underscore}.title", default: i18n.t(:title, default: @exception.class.name)
          h[:message] = i18n.t "#{@exception.class.name.underscore}.description", default: i18n.t(:description, default: @exception.message)
        end
      end
    end
    helper_method :details

    ####################
    #      Layout      #
    ####################

    private

    #Layout
    def layout_status
      @status.to_s != "404" ? "error" : "application"
    end

    #App
    def app_name
      @app_name = Rails.application.class.parent_name
    end

  end
end

app/controllers/powers_controller.rb
class PowersController < ApplicationController
  before_action :set_power, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! , except: [:index, :show]
  
  $power_Q1_random_a = 2+rand(10)  
  $power_Q1_random_b = 2+rand(4)
  $power_Q2_random_a = 2+rand(8)  
  $power_Q2_random_b = 2+rand(5)
  $power_Q3_random_a = 2+rand(6)  
  $power_Q3_random_b = 2+rand(3)
  $power_Q4_random_a = 2+rand(10) 
  $power_Q4_random_b = 2+rand(4)
  $power_Q5_random_a = 2+rand(8)  
  $power_Q5_random_b = 2+rand(5)
  $power_Q6_random_a = 2+rand(6)  
  $power_Q6_random_b = 2+rand(3)
  $power_Q7_random_a = 2+rand(10) 
  $power_Q7_random_b = 2+rand(4)
  $power_Q8_random_a = 2+rand(8)  
  $power_Q8_random_b = 2+rand(5)
  $power_Q9_random_a = 2+rand(6)  
  $power_Q9_random_b = 2+rand(3)
  $power_Q10_random_a = 2+rand(100) 
  $power_Q10_random_b = 2+rand(200)
  # GET /Power
  # GET /Power.json
  def power   
    @point =0
    #byebug
    @input1 = params[:search_string1]
    @result1 = Power.find_power($power_Q1_random_a, $power_Q1_random_b,  @input1.to_i)
    @resultofpower1 = Power.value_power($power_Q1_random_a, $power_Q1_random_b)
    if (@result1 === 'WELL DONE')
      @point= @point +1 
    end  
    
    @input2 = params[:search_string2]
    @result2 = Power.find_power($power_Q2_random_a, $power_Q2_random_b,  @input2.to_i)
    @resultofpower2 = Power.value_power($power_Q2_random_a, $power_Q2_random_b)
    if (@result2 === 'WELL DONE')
      @point= @point +1 
    end    
    #byebug
    @input3 = params[:search_string3]
    @result3 = Power.find_power($power_Q3_random_a, $power_Q3_random_b,  @input3.to_i)
    @resultofpower3 = Power.value_power($power_Q3_random_a, $power_Q3_random_b)
    if (@result3 === 'WELL DONE')
      @point= @point +1 
    end
     
    @input4 = params[:search_string4]
    @result4 = Power.find_power($power_Q4_random_a, $power_Q4_random_b,  @input4.to_i)
    @resultofpower4 = Power.value_power($power_Q4_random_a, $power_Q4_random_b)
    if (@result4 === 'WELL DONE')
      @point= @point +1 
    end
    
    @input5 = params[:search_string5]
    @result5 = Power.find_power($power_Q5_random_a, $power_Q5_random_b,  @input5.to_i)
    @resultofpower5 = Power.value_power($power_Q5_random_a, $power_Q5_random_b)
    if (@result5 === 'WELL DONE')
      @point= @point +1 
    end
    
    @input6 = params[:search_string6]
    @result6 = Power.find_power($power_Q6_random_a, $power_Q6_random_b,  @input6.to_i)
    @resultofpower6 = Power.value_power($power_Q6_random_a, $power_Q6_random_b)
    if (@result6 === 'WELL DONE')
      @point= @point +1 
    end
    
    @input7 = params[:search_string7]
    @result7 = Power.find_power($power_Q7_random_a, $power_Q7_random_b,  @input7.to_i)
    @resultofpower7 = Power.value_power($power_Q7_random_a, $power_Q7_random_b)
    if (@result7 === 'WELL DONE')
      @point= @point +1 
    end
    
    @input8 = params[:search_string8]
    @result8 = Power.find_power($power_Q8_random_a, $power_Q8_random_b,  @input8.to_i)
    @resultofpower8 = Power.value_power($power_Q8_random_a, $power_Q8_random_b)
    if (@result8 === 'WELL DONE')
      @point= @point +1 
    end
    
    @input9 = params[:search_string9]
    @result9 = Power.find_power($power_Q9_random_a, $power_Q9_random_b,  @input9.to_i)
    @resultofpower9 = Power.value_power($power_Q9_random_a, $power_Q9_random_b)
    if (@result9 === 'WELL DONE')
      @point= @point +1 
    end
   # byebug
		@input10 = params[:search_string10].to_i
		@result10 = Checkpercentage.find_amount($power_Q10_random_a, $power_Q10_random_b)	
		if(@input10 == @result10)
      @print = "WELL DONE" 
			@point= @point+1
		else
      @print = "WRONG" 
    end
			
			
    
    @final_points = Point.find_point(@point)
    
  end # End of Def opower
  
  # GET /powers
  # GET /powers.json
  def index
   # @powers = Power.all
    return :index
  end

  # GET /powers/1
  # GET /powers/1.json
  def show
  end

  # GET /powers/new
  def new
    @power = current_user.powers.build
  end

  # GET /powers/1/edit
  def edit
  end

  # POST /powers
  # POST /powers.json
  def create
    @power = current_user.powers.build(power_params)

    respond_to do |format|
      if @power.save
        format.html { redirect_to @power, notice: 'Power was successfully created.' }
        format.json { render :show, status: :created, location: @power }
      else
        format.html { render :new }
        format.json { render json: @power.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /powers/1
  # PATCH/PUT /powers/1.json
  def update
    respond_to do |format|
      if @power.update(power_params)
        format.html { redirect_to @power, notice: 'Power was successfully updated.' }
        format.json { render :show, status: :ok, location: @power }
      else
        format.html { render :edit }
        format.json { render json: @power.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /powers/1
  # DELETE /powers/1.json
  def destroy
    @power.destroy
    respond_to do |format|
      format.html { redirect_to powers_url, notice: 'Power was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_power
      @power = Power.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def power_params
      params.require(:power).permit(:powernum)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/powers_helper.rb
module PowersHelper
end

app/views/exception_handler/exception/show.html.erb
<div class="container center">
      <div class="row">
        <div class="col-xs-12">
   
        <% if @status.to_s == "404" %>

	      Sorry, this page is not Available!

	<div class="error">

		<!--Alert -->
		<%= image_tag 'exception_handler/alert.png', width: "150", alt: "Error!", title: "Sorry, A Server Error Occurred", class: "alert" %>
	
		<!--Message 
		<div class="message">
			<strong><%= details[:name] %></strong>
			<span><%= details[:message] %></span>
		</div>-->

		<!--Contact -->
		<div class="contact">
			<% ExceptionHandler.config.social.each do |item, address| %>
				<%= link_to image_tag("exception_handler/contact/#{item}.png", title: item.to_s.titleize), address, target: :blank %>
			<% end %>
		</div>
	</div>
        <%= link_to image_tag("frank.jpg", alt: "Frank image"), 'https://sites.google.com/a/tcd.ie/fslyne/', class: "img-thumbnail" %>
        <%= link_to image_tag("yann.jpg", alt: "Yann image"), 'https://www.smytweb.com/' , class:"img-thumbnail" %>
        <%= link_to image_tag("NCI.png", alt: "NCI image"), 'https://www.ncirl.ie/' , class:"img-thumbnail" %>    
        <%= link_to image_tag("quiz.jpeg", alt: "Quiz image"), '#' , class:"img-thumbnail" %>  
       </div>
      </div>
</div>
          
<% else %>

	<div class="error">

		<!--Alert -->
		<%= image_tag 'exception_handler/alert.png', width: "150", alt: "Error!", title: "Sorry, A Server Error Occurred", class: "alert" %>
	
		<!--Message -->
		<div class="message">
			<strong><%= details[:name] %></strong>
			<span><%= details[:message] %></span>
		</div>

		<!--Contact -->
		<div class="contact">
			<% ExceptionHandler.config.social.each do |item, address| %>
				<%= link_to image_tag("exception_handler/contact/#{item}.png", title: item.to_s.titleize), address, target: :blank %>
			<% end %>
		</div>
		
	</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YANN MATH APP</title>
     <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
     <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
     <%= csrf_meta_tags %>
     <%= render 'shared/shim' %>
  </head>
  <body>
    <%= render 'shared/navigation' %>
     <div class="container">
        <% flash.each do |name, msg| -%>
        <%= content_tag :div, msg, class: "alert alert-#{name}" %>
        <% end -%>
        <%= yield %>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/layouts/error.html.erb
<!DOCTYPE html>
<html>
  <head>

    <!--Info -->
    <title><%= "Error :: #{@app_name}" %></title>

    <!--Styling -->
    <style>
      
		html {
			height: 100%;
			background: #fff asset_url("custom_error_pages/bg.png") bottom repeat-x;
		}
		
		body {
			font-family: Helvetica, Arial, Sans-Serif;
			font-size: 14px;
		}
		.error_container {
			display: block;
			margin: auto;
			margin: 10% auto 0 auto;
			width: 30%;
		}
		
		.error_container .error {
			display: block;
			text-align: center;
		}
		
		.error_container .error img.alert {
			display: block;
			margin: 0 auto 25px auto;
		}
		
		.error_container .message > * {
			display: block;
		}
		
		.error_container .message strong {
			font-weight: bold;
			font-size: 1.5em;
			color: #f00;
			margin: 15px 0 0;
		}

		.error_container .message span {
			margin: 5px auto 0;
			font-size: 0.75em;
			color: #606060;
		}
		
		.error_container .contact {
			display: block;
			text-align: center;
			margin: 20px 0 0 0;
		}
		
		.error_container .contact a {
			display: inline-block;
			margin: 0 -1px; /* For inline block & ERB - HAML removes whitespace; ERB does now - http://haml.info/docs/yardoc/file.REFERENCE.html#whitespace_removal__and_ */
			opacity: 0.4;
			transition: opacity 0.15s ease;
		}

		.error_container .contact a img {
			display: block;
			width: 38px;
			height: 38px;
		}
		
		.error_container .contact a:hover {
			opacity: 0.8;
		}

    </style>
  </head>
  
  <!--Body -->
  <body>
    <div class="error_container">
      <%= yield %>
    </div>
  </body>

</html>

app/views/powers/_form.html.erb
<%= form_for(@power) do |f| %>
  <% if @power.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@power.errors.count, "error") %> prohibited this power from being saved:</h2>

      <ul>
      <% @power.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :powernum %><br>
    <%= f.number_field :powernum %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/powers/checkpower.html.erb
<h1> THE MATH QUIZ </h1>

<div class="center jumbotron">
  <div class="container center">
      <div class="row">
        <div class="col-xs-12">
          <%= form_tag "/validate" do %>
          <p> Q1 - What is the power of <%= $power_Q1_random_a%> over <%= $power_Q1_random_b%> ? 
          <%= text_field_tag :search_string1 %></p>
          <p> Q2 - What is the power of <%= $power_Q2_random_a%> over <%= $power_Q2_random_b%> ? 
          <%= text_field_tag :search_string2 %></p>
          <p> Q3 - What is the power of <%= $power_Q3_random_a%> over <%= $power_Q3_random_b%> ?
          <%= text_field_tag :search_string3 %> </p>
          <p> Q4 - What is the power of <%= $power_Q4_random_a%> over <%= $power_Q4_random_b%> ? 
          <%= text_field_tag :search_string4 %></p>
          <p> Q5 - What is the power of <%= $power_Q5_random_a%> over <%= $power_Q5_random_b%> ? 
          <%= text_field_tag :search_string5 %></p>
          <p> Q6 - What is the power of <%= $power_Q6_random_a%> over <%= $power_Q6_random_b%> ?
          <%= text_field_tag :search_string6 %> </p>
          <p> Q7 - What is the power of <%= $power_Q7_random_a%> over <%= $power_Q7_random_b%> ? 
          <%= text_field_tag :search_string7 %></p>
          <p> Q8 - What is the power of <%= $power_Q8_random_a%> over <%= $power_Q8_random_b%> ? 
          <%= text_field_tag :search_string8 %></p>
          <p> Q9 - What is the power of <%= $power_Q9_random_a%> over <%= $power_Q9_random_b%> ?
          <%= text_field_tag :search_string9 %> </p>
          <p> Q10 - What is <%= $power_Q10_random_a  %> % of <%= $power_Q10_random_b %> ?
          <%= text_field_tag :search_string10 %> </p>

<br />
<br />
<%= submit_tag "SUBMIT" %> 
<br />
</div>
   </div>       
        </div>  
<% end %>

app/views/powers/edit.html.erb
<h1>Editing power</h1>

<%= render 'form' %>

<%= link_to 'Show', @power %> |
<%= link_to 'Back', powers_path %>

app/views/powers/index.html.erb
<div class="center jumbotron">
  <h1>Welcome to Student Math Quiz</h1>

  <h2>
   Before join <a href="https://www.ncirl.ie/">NCI college</a> we need to know your level of Mathematics, 
   Please sign-up and Start the Mathematics QUIZ.
  </h2>
    
  <% if user_signed_in? %>
   <%= link_to "TAKE THE QUIZ!", "/check" , class: "btn btn-lg btn-primary" %>
  <% else %>
   <%= link_to "Sign up now!", new_user_session_path , class: "btn btn-lg btn-primary" %>
  <% end %>
  
</div>
<div class="container center">
      <div class="row">
        <div class="col-xs-12">
        <%= link_to image_tag("frank.jpg", alt: "Frank image"), 'https://sites.google.com/a/tcd.ie/fslyne/', class: "img-thumbnail" %>
        <%= link_to image_tag("yann.jpg", alt: "Yann image"), 'https://www.smytweb.com/' , class:"img-thumbnail" %>
        <%= link_to image_tag("NCI.png", alt: "NCI image"), 'https://www.ncirl.ie/' , class:"img-thumbnail" %>    
        <%= link_to image_tag("quiz.jpeg", alt: "Quiz image"), '#' , class:"img-thumbnail" %>  
       </div>
      </div>
</div>

app/views/powers/new.html.erb
<h1>New power</h1>

<%= render 'form' %>

<%= link_to 'Back', powers_path %>

app/views/powers/power.html.erb
      <h1>RESULT</h1>   
<div class=" center jumbotron">
    <div class="container ">
      <div class="row">
        <div class="col-xs-6  ">
          <p> Q1= The Power of <%= $power_Q1_random_a %> over <%= $power_Q1_random_b %>  is  <%= @resultofpower1 %>. <br>
          You have answered <%= @input1 %>  !!   <%= @result1 %> </p>

          <p> Q2= The Power of <%= $power_Q2_random_a %> over <%= $power_Q2_random_b %>  is  <%= @resultofpower2 %>.<br>
          You have answered <%= @input2 %>  !!   <%= @result2 %> </p> 

          <p> Q3= The Power of <%= $power_Q3_random_a %> over <%= $power_Q3_random_b %>  is  <%= @resultofpower3 %>.<br>
          You have answered <%= @input3 %>  !!    <%= @result3 %> </p> 

          <p> Q4= The Power of <%= $power_Q4_random_a %> over <%= $power_Q4_random_b %>  is  <%= @resultofpower4 %>.<br>
          You have answered <%= @input4 %>  !!    <%= @result4 %> </p> 

          <p> Q5= The Power of <%= $power_Q5_random_a %> over <%= $power_Q5_random_b %>  is  <%= @resultofpower5 %>.<br>
          You have answered <%= @input5 %>  !!    <%= @result5 %> </p> 
       </div> 
        
        <div class="col-xs-6">
          <p> Q6= The Power of <%= $power_Q6_random_a %> over <%= $power_Q6_random_b %>  is  <%= @resultofpower6 %>. <br>
          You have answered <%= @input6 %>  !!   <%= @result6 %> </p>

          <p> Q7= The Power of <%= $power_Q7_random_a %> over <%= $power_Q7_random_b %>  is  <%= @resultofpower7 %>.<br>
          You have answered <%= @input7 %>  !!   <%= @result7 %> </p> 

          <p> Q8= The Power of <%= $power_Q8_random_a %> over <%= $power_Q8_random_b %>  is  <%= @resultofpower8 %>.<br>
          You have answered <%= @input8 %>  !!    <%= @result8 %> </p> 

          <p> Q9= The Power of <%= $power_Q9_random_a %> over <%= $power_Q9_random_b %>  is  <%= @resultofpower9 %>.<br>
          You have answered <%= @input9 %>  !!    <%= @result9 %> </p> 

          <p> Q10= Multiply <%= $power_Q10_random_a  %> with  <%= $power_Q10_random_b %> then divide by 100 = <%= @result10 %>. <br>
          You have answered <%= @input10 %>  !!    <%= @print %> </p> 
       </div>  
                  
       <br />
        <hr>
           <h2> Total Points: <%= @point %></h2>
       <br />
        <hr>
          <h2> FEEDBACK: </h2> <h1><%= @final_points  %> </h1>
                             
         </div> 
        </div> 
      </div> 
   
          

          

app/views/powers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Powernum:</strong>
  <%= @power.powernum %>
</p>

<%= link_to 'Edit', edit_power_path(@power) %> |
<%= link_to 'Back', powers_path %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <small>
    This <a href="https://www.ncirl.ie/">NCI Cloud Project was create </a>
    by <a href="http://www.smytweb.com/">Yann Nogueira</a>
  </small>
  <nav>
    <ul>
      <li><a href="https://sites.google.com/a/tcd.ie/fslyne/">Teacher Frank Slyner</a></li>
    </ul>
  </nav>
</footer>

app/views/shared/_navigation.html.erb
<!-- app/views/shared/_navigation.html.erb -->

<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Yann MATH QUIZ ", '/', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   '/' %></li>
            <li><%= link_to "Register", new_user_registration_path %></li>
             <% if user_signed_in? %>
            <li><%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
             <% else %>
            <li><%= link_to "Log in",  new_user_session_path %></li>
             <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/shared/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->